name: all_legal_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  cached_network_image: ^3.4.1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  
  flutter_svg: ^2.0.10+1
  flutter_test:
    sdk: flutter

    
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter_gen:
  output: lib/src/gen/


  integrations:
    flutter_svg: true

  assets:
    outputs:
      package_parameter_enabled: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/png/

  fonts:
    - family: Geist
      fonts:
        - asset: lib/src/typography/fonts/Geist-Bold.ttf
          weight: 700
        - asset: lib/src/typography/fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: lib/src/typography/fonts/Geist-Medium.ttf
          weight: 500
        - asset: lib/src/typography/fonts/Geist-Regular.ttf
          weight: 400
        - asset: lib/src/typography/fonts/Geist-Light.ttf
          weight: 300
  
          
    - family: AllLegal
      fonts: 
        - asset: assets/icons/AllLegal.ttf 
  

