name: all_legal
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:

  all_legal_ui:
    path: packages/all_legal_ui
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  freezed: ^2.5.7
  go_router: ^14.2.7
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0


flutter:

  uses-material-design: true
  

 

  
    
    
    

  