name: all_legal_core
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.2
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.12
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
